[2024-12-17T06:55:09.187+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_name_dag.clear_xcoms scheduled__2024-12-16T00:00:00+00:00 [queued]>
[2024-12-17T06:55:09.280+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_name_dag.clear_xcoms scheduled__2024-12-16T00:00:00+00:00 [queued]>
[2024-12-17T06:55:09.281+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-12-17T06:55:09.296+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): clear_xcoms> on 2024-12-16 00:00:00+00:00
[2024-12-17T06:55:09.300+0000] {standard_task_runner.py:57} INFO - Started process 10129 to run task
[2024-12-17T06:55:09.303+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'full_name_dag', 'clear_xcoms', 'scheduled__2024-12-16T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/full_name_dag.py', '--cfg-path', '/tmp/tmp7syjalpt']
[2024-12-17T06:55:09.307+0000] {standard_task_runner.py:85} INFO - Job 122: Subtask clear_xcoms
[2024-12-17T06:55:09.326+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-17T06:55:09.364+0000] {task_command.py:415} INFO - Running <TaskInstance: full_name_dag.clear_xcoms scheduled__2024-12-16T00:00:00+00:00 [running]> on host cfbf61ae1f16
[2024-12-17T06:55:09.455+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_name_dag' AIRFLOW_CTX_TASK_ID='clear_xcoms' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-16T00:00:00+00:00'
[2024-12-17T06:55:09.456+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/full_name_dag.py", line 77, in clear_xcoms
    XCom.clear(task_ids='extract_data', dag_id=kwargs['dag'].dag_id, execution_date=kwargs['execution_date'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
TypeError: clear() got an unexpected keyword argument 'task_ids'
[2024-12-17T06:55:09.472+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=full_name_dag, task_id=clear_xcoms, execution_date=20241216T000000, start_date=20241217T065509, end_date=20241217T065509
[2024-12-17T06:55:09.485+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 122 for task clear_xcoms (clear() got an unexpected keyword argument 'task_ids'; 10129)
[2024-12-17T06:55:09.516+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-17T06:55:09.533+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
