[2024-12-20T20:31:05.695+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_name_and_data_users_dag.load_data_2 scheduled__2024-12-16T00:00:00+00:00 [queued]>
[2024-12-20T20:31:05.786+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_name_and_data_users_dag.load_data_2 scheduled__2024-12-16T00:00:00+00:00 [queued]>
[2024-12-20T20:31:05.786+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-12-20T20:31:05.798+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_data_2> on 2024-12-16 00:00:00+00:00
[2024-12-20T20:31:05.802+0000] {standard_task_runner.py:57} INFO - Started process 4139 to run task
[2024-12-20T20:31:05.805+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'full_name_and_data_users_dag', 'load_data_2', 'scheduled__2024-12-16T00:00:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/full_name_data_users_dag.py', '--cfg-path', '/tmp/tmpbivo2017']
[2024-12-20T20:31:05.807+0000] {standard_task_runner.py:85} INFO - Job 169: Subtask load_data_2
[2024-12-20T20:31:05.823+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-20T20:31:05.861+0000] {task_command.py:415} INFO - Running <TaskInstance: full_name_and_data_users_dag.load_data_2 scheduled__2024-12-16T00:00:00+00:00 [running]> on host 150cfac62d06
[2024-12-20T20:31:05.941+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_name_and_data_users_dag' AIRFLOW_CTX_TASK_ID='load_data_2' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-16T00:00:00+00:00'
[2024-12-20T20:31:06.223+0000] {base.py:73} INFO - Using connection ID 'admin' for task execution.
[2024-12-20T20:31:06.256+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/full_name_data_users_dag.py", line 89, in load_data_to_db_2
    session.add(DataUsers(**row.to_dict()))
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 1197, in _declarative_constructor
    raise TypeError(
TypeError: 'num_ud' is an invalid keyword argument for DataUsers
[2024-12-20T20:31:06.267+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=full_name_and_data_users_dag, task_id=load_data_2, execution_date=20241216T000000, start_date=20241220T203105, end_date=20241220T203106
[2024-12-20T20:31:06.288+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 169 for task load_data_2 ('num_ud' is an invalid keyword argument for DataUsers; 4139)
[2024-12-20T20:31:06.299+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-20T20:31:06.318+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
