[2024-12-24T19:24:42.436+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shift_table_sick_leave_dag.load_data_2 manual__2024-12-24T19:24:38.753770+00:00 [queued]>
[2024-12-24T19:24:42.443+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shift_table_sick_leave_dag.load_data_2 manual__2024-12-24T19:24:38.753770+00:00 [queued]>
[2024-12-24T19:24:42.444+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-12-24T19:24:42.455+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_data_2> on 2024-12-24 19:24:38.753770+00:00
[2024-12-24T19:24:42.458+0000] {standard_task_runner.py:57} INFO - Started process 2830 to run task
[2024-12-24T19:24:42.461+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shift_table_sick_leave_dag', 'load_data_2', 'manual__2024-12-24T19:24:38.753770+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/shift_table_sick_leave_dag.py', '--cfg-path', '/tmp/tmpg1zlfsmv']
[2024-12-24T19:24:42.463+0000] {standard_task_runner.py:85} INFO - Job 197: Subtask load_data_2
[2024-12-24T19:24:42.481+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-24T19:24:42.514+0000] {task_command.py:415} INFO - Running <TaskInstance: shift_table_sick_leave_dag.load_data_2 manual__2024-12-24T19:24:38.753770+00:00 [running]> on host e335f8873093
[2024-12-24T19:24:42.589+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shift_table_sick_leave_dag' AIRFLOW_CTX_TASK_ID='load_data_2' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T19:24:38.753770+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T19:24:38.753770+00:00'
[2024-12-24T19:24:42.717+0000] {base.py:73} INFO - Using connection ID 'admin' for task execution.
[2024-12-24T19:24:42.718+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/shift_table_sick_leave_dag.py", line 49, in load_data_to_db_2
    Base.metadata.create_all(engine)
NameError: name 'Base' is not defined
[2024-12-24T19:24:42.731+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=shift_table_sick_leave_dag, task_id=load_data_2, execution_date=20241224T192438, start_date=20241224T192442, end_date=20241224T192442
[2024-12-24T19:24:42.740+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 197 for task load_data_2 (name 'Base' is not defined; 2830)
[2024-12-24T19:24:42.754+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-24T19:24:42.769+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
