[2024-12-24T20:49:36.082+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: education_inventory_medical_object_vocation_dag.load_data manual__2024-12-24T20:49:34.624713+00:00 [queued]>
[2024-12-24T20:49:36.089+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: education_inventory_medical_object_vocation_dag.load_data manual__2024-12-24T20:49:34.624713+00:00 [queued]>
[2024-12-24T20:49:36.090+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-12-24T20:49:36.101+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_data> on 2024-12-24 20:49:34.624713+00:00
[2024-12-24T20:49:36.105+0000] {standard_task_runner.py:57} INFO - Started process 1777 to run task
[2024-12-24T20:49:36.107+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'education_inventory_medical_object_vocation_dag', 'load_data', 'manual__2024-12-24T20:49:34.624713+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/education_inventory_medical_object_vocation_dag.py', '--cfg-path', '/tmp/tmp7x6vqthv']
[2024-12-24T20:49:36.110+0000] {standard_task_runner.py:85} INFO - Job 212: Subtask load_data
[2024-12-24T20:49:36.127+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-24T20:49:36.162+0000] {task_command.py:415} INFO - Running <TaskInstance: education_inventory_medical_object_vocation_dag.load_data manual__2024-12-24T20:49:34.624713+00:00 [running]> on host f7bedf4d7c26
[2024-12-24T20:49:36.238+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='education_inventory_medical_object_vocation_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T20:49:34.624713+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T20:49:34.624713+00:00'
[2024-12-24T20:49:36.449+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/education_inventory_medical_object_vocation_dag.py", line 32, in load_data_to_db
    df = extract_data_from_excel()
  File "/opt/airflow/dags/education_inventory_medical_object_vocation_dag.py", line 27, in extract_data_from_excel
    df_4 = pd.read_excel(xlsx_file_4)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1496, in __init__
    ext = inspect_excel_format(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1371, in inspect_excel_format
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/vacation.xlsx'
[2024-12-24T20:49:36.461+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=education_inventory_medical_object_vocation_dag, task_id=load_data, execution_date=20241224T204934, start_date=20241224T204936, end_date=20241224T204936
[2024-12-24T20:49:36.472+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 212 for task load_data ([Errno 2] No such file or directory: 'data/vacation.xlsx'; 1777)
[2024-12-24T20:49:36.481+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-24T20:49:36.503+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
