[2024-12-16T21:12:18.775+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_name_dag.clear_xcoms manual__2024-12-16T21:07:12.203288+00:00 [queued]>
[2024-12-16T21:12:18.782+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_name_dag.clear_xcoms manual__2024-12-16T21:07:12.203288+00:00 [queued]>
[2024-12-16T21:12:18.783+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-12-16T21:12:18.797+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): clear_xcoms> on 2024-12-16 21:07:12.203288+00:00
[2024-12-16T21:12:18.803+0000] {standard_task_runner.py:57} INFO - Started process 9393 to run task
[2024-12-16T21:12:18.805+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'full_name_dag', 'clear_xcoms', 'manual__2024-12-16T21:07:12.203288+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/full_name_dag.py', '--cfg-path', '/tmp/tmp1o7kvvdr']
[2024-12-16T21:12:18.807+0000] {standard_task_runner.py:85} INFO - Job 111: Subtask clear_xcoms
[2024-12-16T21:12:18.824+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-16T21:12:18.859+0000] {task_command.py:415} INFO - Running <TaskInstance: full_name_dag.clear_xcoms manual__2024-12-16T21:07:12.203288+00:00 [running]> on host cfbf61ae1f16
[2024-12-16T21:12:18.940+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_name_dag' AIRFLOW_CTX_TASK_ID='clear_xcoms' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T21:07:12.203288+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T21:07:12.203288+00:00'
[2024-12-16T21:12:18.941+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/full_name_dag.py", line 78, in clear_xcoms
    XCom.clear(task_ids='extract_data', dag_id=kwargs['dag'].dag_id, execution_date=kwargs['execution_date'])
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
TypeError: clear() got an unexpected keyword argument 'task_ids'
[2024-12-16T21:12:18.954+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=full_name_dag, task_id=clear_xcoms, execution_date=20241216T210712, start_date=20241216T211218, end_date=20241216T211218
[2024-12-16T21:12:18.963+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 111 for task clear_xcoms (clear() got an unexpected keyword argument 'task_ids'; 9393)
[2024-12-16T21:12:18.977+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-16T21:12:18.993+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
