[2024-12-24T20:54:32.055+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: education_inventory_medical_object_vocation_dag.load_data scheduled__2024-12-16T06:00:00+00:00 [queued]>
[2024-12-24T20:54:32.061+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: education_inventory_medical_object_vocation_dag.load_data scheduled__2024-12-16T06:00:00+00:00 [queued]>
[2024-12-24T20:54:32.062+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-12-24T20:54:32.074+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_data> on 2024-12-16 06:00:00+00:00
[2024-12-24T20:54:32.078+0000] {standard_task_runner.py:57} INFO - Started process 2121 to run task
[2024-12-24T20:54:32.081+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'education_inventory_medical_object_vocation_dag', 'load_data', 'scheduled__2024-12-16T06:00:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/education_inventory_medical_object_vocation_dag.py', '--cfg-path', '/tmp/tmpm3tfozv9']
[2024-12-24T20:54:32.083+0000] {standard_task_runner.py:85} INFO - Job 214: Subtask load_data
[2024-12-24T20:54:32.100+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-24T20:54:32.136+0000] {task_command.py:415} INFO - Running <TaskInstance: education_inventory_medical_object_vocation_dag.load_data scheduled__2024-12-16T06:00:00+00:00 [running]> on host f7bedf4d7c26
[2024-12-24T20:54:32.213+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='education_inventory_medical_object_vocation_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-16T06:00:00+00:00'
[2024-12-24T20:54:32.533+0000] {base.py:73} INFO - Using connection ID 'admin' for task execution.
[2024-12-24T20:54:32.534+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/education_inventory_medical_object_vocation_dag.py", line 36, in load_data_to_db
    for row in df.iterrows():
AttributeError: 'tuple' object has no attribute 'iterrows'
[2024-12-24T20:54:32.546+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=education_inventory_medical_object_vocation_dag, task_id=load_data, execution_date=20241216T060000, start_date=20241224T205432, end_date=20241224T205432
[2024-12-24T20:54:32.556+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 214 for task load_data ('tuple' object has no attribute 'iterrows'; 2121)
[2024-12-24T20:54:32.572+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-24T20:54:32.598+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
