[2024-12-12T20:00:19.395+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_postgres_connection.test_postgres_connection manual__2024-12-12T20:00:17.867425+00:00 [queued]>
[2024-12-12T20:00:19.401+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_postgres_connection.test_postgres_connection manual__2024-12-12T20:00:17.867425+00:00 [queued]>
[2024-12-12T20:00:19.402+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-12-12T20:00:19.414+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): test_postgres_connection> on 2024-12-12 20:00:17.867425+00:00
[2024-12-12T20:00:19.418+0000] {standard_task_runner.py:57} INFO - Started process 260 to run task
[2024-12-12T20:00:19.420+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_postgres_connection', 'test_postgres_connection', 'manual__2024-12-12T20:00:17.867425+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpxel1okhq']
[2024-12-12T20:00:19.423+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask test_postgres_connection
[2024-12-12T20:00:19.441+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-12T20:00:19.476+0000] {task_command.py:415} INFO - Running <TaskInstance: test_postgres_connection.test_postgres_connection manual__2024-12-12T20:00:17.867425+00:00 [running]> on host af7f9afe6e38
[2024-12-12T20:00:19.553+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_postgres_connection' AIRFLOW_CTX_TASK_ID='test_postgres_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T20:00:17.867425+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-12T20:00:17.867425+00:00'
[2024-12-12T20:00:19.554+0000] {sql.py:274} INFO - Executing: SELECT 1;
[2024-12-12T20:00:19.564+0000] {base.py:73} INFO - Using connection ID 'admin' for task execution.
[2024-12-12T20:00:19.574+0000] {base.py:73} INFO - Using connection ID 'admin' for task execution.
[2024-12-12T20:00:27.580+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "***" to address: Temporary failure in name resolution

[2024-12-12T20:00:27.591+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=test_postgres_connection, task_id=test_postgres_connection, execution_date=20241212T200017, start_date=20241212T200019, end_date=20241212T200027
[2024-12-12T20:00:27.601+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task test_postgres_connection (could not translate host name "***" to address: Temporary failure in name resolution
; 260)
[2024-12-12T20:00:27.639+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-12T20:00:27.653+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
